import { describe, it, expect } from "vitest";
import { isAutoGeneratedId, generateAutoId } from "./screenItemNaming";

// ---------------------------------------------------------------------------
// isAutoGeneratedId
// ---------------------------------------------------------------------------
describe("isAutoGeneratedId", () => {
  // 旧自動採番 (field_ + 8 hex)
  it("field_ + 8 hex → true", () => {
    expect(isAutoGeneratedId("field_69f9561e")).toBe(true);
    expect(isAutoGeneratedId("field_abcd1234")).toBe(true);
    expect(isAutoGeneratedId("field_00000000")).toBe(true);
  });

  it("field_ + 7 hex → false (桁不足)", () => {
    expect(isAutoGeneratedId("field_1234567")).toBe(false);
  });

  it("field_ + 9 hex → false (桁超過)", () => {
    expect(isAutoGeneratedId("field_123456789")).toBe(false);
  });

  it("field_ + 非 hex 文字 → false", () => {
    expect(isAutoGeneratedId("field_xyz12345")).toBe(false);
    expect(isAutoGeneratedId("field_ABCD1234")).toBe(false);
  });

  // 種別+連番
  it("textInput + 連番 → true", () => {
    expect(isAutoGeneratedId("textInput1")).toBe(true);
    expect(isAutoGeneratedId("textInput10")).toBe(true);
    expect(isAutoGeneratedId("textInput99")).toBe(true);
  });

  it("passwordInput + 連番 → true", () => {
    expect(isAutoGeneratedId("passwordInput1")).toBe(true);
  });

  it("numberInput + 連番 → true", () => {
    expect(isAutoGeneratedId("numberInput1")).toBe(true);
  });

  it("textarea + 連番 → true", () => {
    expect(isAutoGeneratedId("textarea1")).toBe(true);
  });

  it("select + 連番 → true", () => {
    expect(isAutoGeneratedId("select1")).toBe(true);
    expect(isAutoGeneratedId("select2")).toBe(true);
  });

  it("checkbox + 連番 → true", () => {
    expect(isAutoGeneratedId("checkbox1")).toBe(true);
  });

  it("radio + 連番 → true", () => {
    expect(isAutoGeneratedId("radio3")).toBe(true);
  });

  it("button + 連番 → true", () => {
    expect(isAutoGeneratedId("button1")).toBe(true);
  });

  it("dateInput + 連番 → true", () => {
    expect(isAutoGeneratedId("dateInput1")).toBe(true);
  });

  it("datetimeInput + 連番 → true", () => {
    expect(isAutoGeneratedId("datetimeInput1")).toBe(true);
  });

  it("timeInput / emailInput / telInput 等 → true", () => {
    expect(isAutoGeneratedId("timeInput1")).toBe(true);
    expect(isAutoGeneratedId("emailInput2")).toBe(true);
    expect(isAutoGeneratedId("telInput1")).toBe(true);
    expect(isAutoGeneratedId("urlInput1")).toBe(true);
    expect(isAutoGeneratedId("fileInput1")).toBe(true);
    expect(isAutoGeneratedId("monthInput1")).toBe(true);
    expect(isAutoGeneratedId("weekInput1")).toBe(true);
  });

  it("field + 連番 (アンダースコアなし) → true", () => {
    expect(isAutoGeneratedId("field1")).toBe(true);
    expect(isAutoGeneratedId("field99")).toBe(true);
  });

  // 命名済み (上書き禁止)
  it("ユーザ命名 → false", () => {
    expect(isAutoGeneratedId("userName")).toBe(false);
    expect(isAutoGeneratedId("postalCode")).toBe(false);
    expect(isAutoGeneratedId("loginBtn")).toBe(false);
  });

  it("日本語 → false", () => {
    expect(isAutoGeneratedId("ユーザ名")).toBe(false);
    expect(isAutoGeneratedId("郵便番号")).toBe(false);
  });

  it("空文字 → false", () => {
    expect(isAutoGeneratedId("")).toBe(false);
  });

  it("prefix だけで連番なし → false (textInput のみ)", () => {
    expect(isAutoGeneratedId("textInput")).toBe(false);
    expect(isAutoGeneratedId("select")).toBe(false);
  });

  it("prefix に似ているが別語 → false (textInputValue 等)", () => {
    expect(isAutoGeneratedId("textInputValue")).toBe(false);
    expect(isAutoGeneratedId("textInput1Extra")).toBe(false);
  });

  it("連番 0 → true (\\d+ は 0 を含む)", () => {
    expect(isAutoGeneratedId("textInput0")).toBe(true);
  });

  it("10 桁以上の連番 → true", () => {
    expect(isAutoGeneratedId("textInput1234567890")).toBe(true);
  });
});

// ---------------------------------------------------------------------------
// generateAutoId
// ---------------------------------------------------------------------------
describe("generateAutoId", () => {
  it("既存なし → prefix1", () => {
    expect(generateAutoId("textInput", [])).toBe("textInput1");
    expect(generateAutoId("select", [])).toBe("select1");
  });

  it("最大連番 +1 を返す", () => {
    expect(generateAutoId("textInput", ["textInput1", "textInput3"])).toBe("textInput4");
  });

  it("同じ prefix の最大値のみカウント (他 prefix は無視)", () => {
    expect(generateAutoId("select", ["textInput1", "textInput2"])).toBe("select1");
  });

  it("旧形式 field_xxx が混在しても破綻しない", () => {
    expect(generateAutoId("textInput", ["field_abc12345", "textInput1"])).toBe("textInput2");
  });

  it("ユーザ命名が混在しても破綻しない", () => {
    expect(generateAutoId("textInput", ["userName", "textInput2"])).toBe("textInput3");
  });

  it("連番が飛んでいても max+1 を返す", () => {
    expect(generateAutoId("button", ["button1", "button5"])).toBe("button6");
  });
});
