/**
 * 画面項目 ID の「自動生成 / 命名済み」判定と自動採番ロジック (#333)。
 *
 * 自動生成 ID パターン:
 *   - 旧自動採番: field_[0-9a-f]{8}  (field_69f9561e 等)
 *   - 種別+連番:  <prefix><数字>      (textInput1, select3 等)
 *
 * それ以外 (userName, 郵便番号, etc.) は「命名済み」として上書き禁止。
 */
import type { FieldType } from "../types/v3";

const OLD_AUTO_PATTERN = /^field_[0-9a-f]{8}$/;

/** getItemIdPrefix が返しうる全プレフィックスと "field"(連番形式) */
const SEQUENTIAL_PREFIXES = [
  // 入力系
  "textInput", "passwordInput", "numberInput",
  "dateInput", "datetimeInput", "timeInput", "monthInput", "weekInput",
  "emailInput", "telInput", "urlInput", "fileInput",
  "checkbox", "radio", "textarea", "select", "button", "field",
  // 出力系 (#359)
  "textDisplay", "valueLabel", "statusBadge", "tableView",
];

const SEQUENTIAL_PATTERN = new RegExp(
  `^(${SEQUENTIAL_PREFIXES.join("|")})\\d+$`,
);

/**
 * ID が自動生成済み (上書き可) かどうかを返す。
 * - 旧自動採番 (`field_xxxxxxxx`) → true
 * - 種別+連番 (`textInput1` 等) → true
 * - それ以外 → false (命名済み、保護対象)
 */
export function isAutoGeneratedId(id: string): boolean {
  return OLD_AUTO_PATTERN.test(id) || SEQUENTIAL_PATTERN.test(id);
}

/**
 * 指定プレフィックスの次の連番 ID を返す。
 * existing に `prefix + 数字` の形式が含まれていれば最大値 +1、
 * なければ `prefix1` を返す。
 */
export function generateAutoId(prefix: string, existing: string[]): string {
  const pattern = new RegExp(`^${prefix}(\\d+)$`);
  let maxN = 0;
  for (const id of existing) {
    const m = id.match(pattern);
    if (m) maxN = Math.max(maxN, parseInt(m[1], 10));
  }
  return `${prefix}${maxN + 1}`;
}

/**
 * ScreenItem の型 (FieldType) から命名プレフィックスを返す (#334)。
 * GrapesJS 要素の HTML タイプと 1:1 ではなく、論理的なデータ型から最も近いプレフィックスを選択。
 */
export function getFieldTypePrefix(type: FieldType): string {
  if (typeof type !== "string") return "field";
  switch (type) {
    case "number":
    case "integer": return "numberInput";
    case "boolean": return "checkbox";
    case "date": return "dateInput";
    case "datetime": return "datetimeInput";
    default: return "textInput";
  }
}
