/**
 * getRenameContext / applyRenameMapping の単体テスト (#335)。
 */
import { describe, it, expect, vi, beforeEach } from "vitest";
import type { GetRenameContextResult, ApplyRenameMappingResult } from "./renameContext.js";

// ── インメモリストレージ ──────────────────────────────────────────────────

const store: {
  screenItems: Record<string, unknown>;
  screens: Record<string, unknown>;
  processFlows: Record<string, unknown>;
} = { screenItems: {}, screens: {}, processFlows: {} };

function resetStore() {
  store.screenItems = {};
  store.screens = {};
  store.processFlows = {};
}

vi.mock("./projectStorage.js", () => ({
  readScreenItems:  (id: string) => Promise.resolve(store.screenItems[id] ?? null),
  writeScreenItems: (id: string, data: unknown) => { store.screenItems[id] = data; return Promise.resolve(); },
  readScreen:       (id: string) => Promise.resolve(store.screens[id] ?? null),
  writeScreen:      (id: string, data: unknown) => { store.screens[id] = data; return Promise.resolve(); },
  listProcessFlows: () => Promise.resolve(Object.values(store.processFlows)),
  readProcessFlow:  (id: string) => Promise.resolve(store.processFlows[id] ?? null),
  writeProcessFlow: (id: string, data: unknown) => { store.processFlows[id] = data; return Promise.resolve(); },
}));

import { isAutoGeneratedId, getRenameContext, applyRenameMapping } from "./renameContext.js";

const TEST_ROOT = "/test-root";

const SCREEN_ID = "screen-ctx-001";

beforeEach(() => resetStore());

// ── isAutoGeneratedId ────────────────────────────────────────────────────────

describe("isAutoGeneratedId", () => {
  it("旧自動採番 (field_xxxxxxxx) → true", () => {
    expect(isAutoGeneratedId("field_69f9561e")).toBe(true);
    expect(isAutoGeneratedId("field_00000000")).toBe(true);
  });

  it("種別+連番 → true", () => {
    expect(isAutoGeneratedId("textInput1")).toBe(true);
    expect(isAutoGeneratedId("select3")).toBe(true);
    expect(isAutoGeneratedId("checkbox1")).toBe(true);
    expect(isAutoGeneratedId("button99")).toBe(true);
  });

  it("業務命名 → false", () => {
    expect(isAutoGeneratedId("userName")).toBe(false);
    expect(isAutoGeneratedId("postalCode")).toBe(false);
    expect(isAutoGeneratedId("email")).toBe(false);
  });

  it("プレフィックスのみ (数字なし) → false", () => {
    expect(isAutoGeneratedId("textInput")).toBe(false);
    expect(isAutoGeneratedId("select")).toBe(false);
  });

  it("field_ + 7桁 (旧形式外) → false", () => {
    expect(isAutoGeneratedId("field_1234567")).toBe(false);
  });
});

// ── getRenameContext ─────────────────────────────────────────────────────────

describe("getRenameContext", () => {
  it("screen-items なし → 空リスト", async () => {
    const result = await getRenameContext(SCREEN_ID, TEST_ROOT);
    expect(result.unnamedItems).toHaveLength(0);
    expect(result.namedCount).toBe(0);
  });

  it("items が空配列 → 空リスト", async () => {
    store.screenItems[SCREEN_ID] = {
      screenId: SCREEN_ID,
      updatedAt: "2026-01-01T00:00:00.000Z",
      items: [],
    };
    const result = await getRenameContext(SCREEN_ID, TEST_ROOT);
    expect(result.unnamedItems).toHaveLength(0);
    expect(result.namedCount).toBe(0);
  });

  it("全て命名済み → unnamedItems 空、namedCount = 項目数", async () => {
    store.screenItems[SCREEN_ID] = {
      screenId: SCREEN_ID,
      updatedAt: "2026-01-01T00:00:00.000Z",
      items: [
        { id: "userName",   label: "氏名",     type: "string" },
        { id: "postalCode", label: "郵便番号", type: "string" },
      ],
    };
    const result = await getRenameContext(SCREEN_ID, TEST_ROOT);
    expect(result.unnamedItems).toHaveLength(0);
    expect(result.namedCount).toBe(2);
  });

  it("全て未命名 → unnamedItems に全件", async () => {
    store.screenItems[SCREEN_ID] = {
      screenId: SCREEN_ID,
      updatedAt: "2026-01-01T00:00:00.000Z",
      items: [
        { id: "textInput1",  label: "氏名",   type: "string" },
        { id: "textInput2",  label: "住所",   type: "string" },
      ],
    };
    const result = await getRenameContext(SCREEN_ID, TEST_ROOT);
    expect(result.unnamedItems).toHaveLength(2);
    expect(result.namedCount).toBe(0);
  });

  it("命名済みと未命名が混在 → 未命名のみ返す", async () => {
    store.screenItems[SCREEN_ID] = {
      screenId: SCREEN_ID,
      updatedAt: "2026-01-01T00:00:00.000Z",
      items: [
        { id: "textInput1",  label: "氏名",     type: "string" },  // 未命名
        { id: "email",       label: "メール",   type: "string" },  // 命名済
        { id: "select1",     label: "種別",     type: "string" },  // 未命名
      ],
    };
    const result: GetRenameContextResult = await getRenameContext(SCREEN_ID, TEST_ROOT);
    expect(result.unnamedItems).toHaveLength(2);
    expect(result.unnamedItems.map((i) => i.id)).toEqual(["textInput1", "select1"]);
    expect(result.namedCount).toBe(1);
  });

  it("HTML 断片: 画面 HTML が文字列の場合、周辺 HTML を返す", async () => {
    store.screenItems[SCREEN_ID] = {
      screenId: SCREEN_ID,
      updatedAt: "2026-01-01T00:00:00.000Z",
      items: [{ id: "textInput1", label: "氏名", type: "string" }],
    };
    store.screens[SCREEN_ID] = {
      pages: [{
        frames: [{
          component: {
            type: "wrapper",
            components: `<div><h3>ユーザー情報</h3><label>氏名</label><input name="textInput1" id="textInput1" placeholder="お名前"></div>`,
          },
        }],
      }],
    };
    const result = await getRenameContext(SCREEN_ID, TEST_ROOT);
    const item = result.unnamedItems[0];
    expect(item.htmlFragment).toContain("textInput1");
  });

  it("HTML 断片: 画面 HTML がコンポーネントオブジェクトの場合も抽出できる", async () => {
    store.screenItems[SCREEN_ID] = {
      screenId: SCREEN_ID,
      updatedAt: "2026-01-01T00:00:00.000Z",
      items: [{ id: "textInput1", label: "氏名", type: "string" }],
    };
    store.screens[SCREEN_ID] = {
      pages: [{
        frames: [{
          component: {
            type: "wrapper",
            components: [
              { tagName: "h3", components: [{ type: "textnode", content: "顧客情報" }] },
              {
                tagName: "input",
                attributes: { name: "textInput1", id: "textInput1", type: "text", placeholder: "お名前" },
              },
            ],
          },
        }],
      }],
    };
    const result = await getRenameContext(SCREEN_ID, TEST_ROOT);
    const item = result.unnamedItems[0];
    expect(item.htmlFragment).toContain("textInput1");
    expect(item.headingContext).toContain("顧客情報");
  });

  it("画面ファイルなし → htmlFragment/headingContext が空でも正常終了", async () => {
    store.screenItems[SCREEN_ID] = {
      screenId: SCREEN_ID,
      updatedAt: "2026-01-01T00:00:00.000Z",
      items: [{ id: "textInput1", label: "氏名", type: "string" }],
    };
    // screens はセットしない
    const result = await getRenameContext(SCREEN_ID, TEST_ROOT);
    expect(result.unnamedItems).toHaveLength(1);
    expect(result.unnamedItems[0].htmlFragment).toBe("");
    expect(result.unnamedItems[0].headingContext).toEqual([]);
  });

  it("validation-input (tagName なし) の htmlFragment が取得できる (#357)", async () => {
    store.screenItems[SCREEN_ID] = {
      screenId: SCREEN_ID,
      updatedAt: "2026-01-01T00:00:00.000Z",
      items: [{ id: "textInput1", label: "氏名", type: "string" }],
    };
    store.screens[SCREEN_ID] = {
      pages: [{
        frames: [{
          component: {
            type: "wrapper",
            components: [
              { tagName: "h3", components: [{ type: "textnode", content: "ユーザー情報" }] },
              {
                type: "validation-input",
                void: true,
                attributes: { type: "text", id: "textInput1", name: "textInput1", placeholder: "お名前" },
              },
            ],
          },
        }],
      }],
    };
    const result = await getRenameContext(SCREEN_ID, TEST_ROOT);
    expect(result.unnamedItems).toHaveLength(1);
    const item = result.unnamedItems[0];
    // void-element として <input ...> が正しく出力されることを確認
    expect(item.htmlFragment).toMatch(/<input[^>]*id="textInput1"/);
    expect(item.headingContext).toContain("ユーザー情報");
  });

  it("validation-select / validation-textarea も HTML 断片に含まれる (#357)", async () => {
    store.screenItems[SCREEN_ID] = {
      screenId: SCREEN_ID,
      updatedAt: "2026-01-01T00:00:00.000Z",
      items: [
        { id: "select1",   label: "種別",     type: "string" },
        { id: "textarea1", label: "備考",     type: "string" },
      ],
    };
    store.screens[SCREEN_ID] = {
      pages: [{
        frames: [{
          component: {
            type: "wrapper",
            components: [
              { type: "validation-select",   attributes: { id: "select1",   name: "select1" } },
              { type: "validation-textarea", attributes: { id: "textarea1", name: "textarea1" } },
            ],
          },
        }],
      }],
    };
    const result = await getRenameContext(SCREEN_ID, TEST_ROOT);
    expect(result.unnamedItems).toHaveLength(2);
    const selectItem   = result.unnamedItems.find((i) => i.id === "select1");
    const textareaItem = result.unnamedItems.find((i) => i.id === "textarea1");
    expect(selectItem?.htmlFragment).toContain("select1");
    expect(textareaItem?.htmlFragment).toContain("textarea1");
  });

  it("label / placeholder が screen-items から引き継がれる", async () => {
    store.screenItems[SCREEN_ID] = {
      screenId: SCREEN_ID,
      updatedAt: "2026-01-01T00:00:00.000Z",
      items: [{ id: "textInput1", label: "郵便番号", type: "string", placeholder: "例: 123-4567" }],
    };
    const result = await getRenameContext(SCREEN_ID, TEST_ROOT);
    expect(result.unnamedItems[0].label).toBe("郵便番号");
    expect(result.unnamedItems[0].placeholder).toBe("例: 123-4567");
  });
});

// ── applyRenameMapping ───────────────────────────────────────────────────────

describe("applyRenameMapping", () => {
  const BASE_ITEMS = () => ({
    screenId: SCREEN_ID,
    updatedAt: "2026-01-01T00:00:00.000Z",
    items: [
      { id: "textInput1", label: "氏名",   type: "string" },
      { id: "textInput2", label: "住所",   type: "string" },
      { id: "select1",    label: "種別",   type: "string" },
    ],
  });

  it("全件成功 → succeeded に 3 件", async () => {
    store.screenItems[SCREEN_ID] = BASE_ITEMS();
    const result: ApplyRenameMappingResult = await applyRenameMapping(SCREEN_ID, {
      textInput1: "fullName",
      textInput2: "address",
      select1:    "category",
    }, TEST_ROOT);
    expect(result.succeeded).toHaveLength(3);
    expect(result.failed).toHaveLength(0);
    const ids = result.succeeded.map((s) => s.newId);
    expect(ids).toContain("fullName");
    expect(ids).toContain("address");
    expect(ids).toContain("category");
  });

  it("screen-items の id が実際に更新される (#332 の renameScreenItemId を経由)", async () => {
    store.screenItems[SCREEN_ID] = BASE_ITEMS();
    await applyRenameMapping(SCREEN_ID, { textInput1: "fullName" }, TEST_ROOT);
    const updated = store.screenItems[SCREEN_ID] as { items: Array<{ id: string }> };
    expect(updated.items.map((i) => i.id)).toContain("fullName");
    expect(updated.items.map((i) => i.id)).not.toContain("textInput1");
  });

  it("存在しない oldId → failed に記録、他は続行", async () => {
    store.screenItems[SCREEN_ID] = BASE_ITEMS();
    const result = await applyRenameMapping(SCREEN_ID, {
      nonExistent: "something",
      textInput1:  "fullName",
    }, TEST_ROOT);
    expect(result.failed).toHaveLength(1);
    expect(result.failed[0].oldId).toBe("nonExistent");
    expect(result.succeeded).toHaveLength(1);
    expect(result.succeeded[0].newId).toBe("fullName");
  });

  it("無効な newId (数字始まり) → failed に記録", async () => {
    store.screenItems[SCREEN_ID] = BASE_ITEMS();
    const result = await applyRenameMapping(SCREEN_ID, {
      textInput1: "123invalid",
    }, TEST_ROOT);
    expect(result.failed).toHaveLength(1);
    expect(result.failed[0].error).toMatch(/識別子/);
  });

  it("newId が既存 id と衝突 → failed に記録", async () => {
    store.screenItems[SCREEN_ID] = BASE_ITEMS();
    const result = await applyRenameMapping(SCREEN_ID, {
      textInput1: "textInput2",  // 既存
    }, TEST_ROOT);
    expect(result.failed).toHaveLength(1);
    expect(result.failed[0].error).toMatch(/既に/);
  });

  it("処理フロー参照も追従 (succeeded.refsRenamed に件数)", async () => {
    store.screenItems[SCREEN_ID] = BASE_ITEMS();
    store.processFlows["ag-001"] = {
      id: "ag-001",
      name: "登録処理",
      actions: [{
        inputs: [{
          name: "textInput1",
          screenItemRef: { screenId: SCREEN_ID, itemId: "textInput1" },
        }],
      }],
    };
    const result = await applyRenameMapping(SCREEN_ID, { textInput1: "fullName" }, TEST_ROOT);
    expect(result.succeeded).toHaveLength(1);
    expect(result.succeeded[0].refsRenamed).toBe(1);
    expect(result.succeeded[0].processFlowsUpdated).toContain("ag-001");
  });

  it("空の mapping → succeeded/failed ともに空", async () => {
    store.screenItems[SCREEN_ID] = BASE_ITEMS();
    const result = await applyRenameMapping(SCREEN_ID, {}, TEST_ROOT);
    expect(result.succeeded).toHaveLength(0);
    expect(result.failed).toHaveLength(0);
  });

  it("newId が JS 予約語 → succeeded に入り warnings に記録される", async () => {
    store.screenItems[SCREEN_ID] = BASE_ITEMS();
    const result = await applyRenameMapping(SCREEN_ID, { textInput1: "let" }, TEST_ROOT);
    // JS 予約語はエラーではなく警告のみ (renameScreenItemId の仕様)
    expect(result.failed).toHaveLength(0);
    expect(result.succeeded).toHaveLength(1);
    expect(result.succeeded[0].newId).toBe("let");
    expect(result.succeeded[0].warnings.length).toBeGreaterThan(0);
    expect(result.succeeded[0].warnings[0]).toMatch(/予約語/);
  });
});
