/**
 * AI 推論による画面項目 ID 再命名のためのコンテキスト収集と一括適用 (#335)。
 *
 * - getRenameContext: 未命名項目の一覧と周辺 HTML コンテキストを返す
 * - applyRenameMapping: mapping を受け取り renameScreenItemId を順次実行する
 *
 * isAutoGeneratedId は designer/src/utils/screenItemNaming.ts (#333) と同一ロジック。
 * designer-mcp は独立パッケージのため複製して保持する。
 */
import { readScreenItems, readScreen } from "./projectStorage.js";
import { renameScreenItemId, type RenameResult } from "./renameScreenItem.js";

// ── 自動生成 ID 判定 (designer/src/utils/screenItemNaming.ts と同一) ─────────

const OLD_AUTO_PATTERN = /^field_[0-9a-f]{8}$/;

const SEQUENTIAL_PREFIXES = [
  "textInput", "passwordInput", "numberInput",
  "dateInput", "datetimeInput", "timeInput", "monthInput", "weekInput",
  "emailInput", "telInput", "urlInput", "fileInput",
  "checkbox", "radio", "textarea", "select", "button", "field",
];

const SEQUENTIAL_PATTERN = new RegExp(
  `^(${SEQUENTIAL_PREFIXES.join("|")})\\d+$`,
);

export function isAutoGeneratedId(id: string): boolean {
  return OLD_AUTO_PATTERN.test(id) || SEQUENTIAL_PATTERN.test(id);
}

// ── GrapesJS コンポーネントツリー → HTML 文字列 ────────────────────────────

const VOID_TAGS = new Set([
  "area", "base", "br", "col", "embed", "hr", "img", "input",
  "link", "meta", "param", "source", "track", "wbr",
]);

const CUSTOM_TYPE_TO_TAG: Record<string, string> = {
  "validation-input": "input",
  "validation-select": "select",
  "validation-textarea": "textarea",
  "checkbox": "input",
};

function serializeComponent(val: unknown): string {
  if (!val) return "";
  if (typeof val === "string") return val;
  if (Array.isArray(val)) return val.map(serializeComponent).join("");

  const c = val as Record<string, unknown>;

  if (c.type === "textnode") return String(c.content ?? "");
  if (c.type === "comment") return `<!--${c.content ?? ""}-->`;

  const tag = typeof c.tagName === "string"
    ? c.tagName
    : (typeof c.type === "string" ? (CUSTOM_TYPE_TO_TAG[c.type] ?? null) : null);
  if (!tag) {
    // wrapper など tagName なし → 子だけ
    return serializeComponent(c.components);
  }

  const attrs = c.attributes as Record<string, unknown> | undefined;
  let attrStr = "";
  if (attrs) {
    attrStr = Object.entries(attrs)
      .map(([k, v]) => (v === true || v === "") ? k : `${k}="${v}"`)
      .join(" ");
    if (attrStr) attrStr = " " + attrStr;
  }

  if (VOID_TAGS.has(tag.toLowerCase())) {
    return `<${tag}${attrStr}>`;
  }

  const inner = serializeComponent(c.components) + (typeof c.content === "string" ? c.content : "");
  return `<${tag}${attrStr}>${inner}</${tag}>`;
}

// GrapesJS ページ構造から HTML 文字列を取得
function screenToHtml(screenDoc: unknown): string {
  if (!screenDoc || typeof screenDoc !== "object") return "";
  const doc = screenDoc as Record<string, unknown>;
  const pages = doc.pages;
  if (!Array.isArray(pages) || pages.length === 0) return "";
  const page = pages[0] as Record<string, unknown>;
  const frames = page.frames;
  if (!Array.isArray(frames) || frames.length === 0) return "";
  const frame = frames[0] as Record<string, unknown>;
  const component = (frame.component as Record<string, unknown> | undefined) ?? {};
  return serializeComponent(component.components ?? "");
}

// ── HTML コンテキスト抽出 ────────────────────────────────────────────────────

function escapeRegex(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function extractHtmlFragment(html: string, itemId: string, windowBefore = 500, windowAfter = 200): string {
  const esc = escapeRegex(itemId);
  const re = new RegExp(`(?:name|id)=["']${esc}["']`);
  const m = re.exec(html);
  if (!m) return "";
  const elementStart = html.lastIndexOf("<", m.index);
  const start = Math.max(0, elementStart - windowBefore);
  const end = Math.min(html.length, m.index + windowAfter);
  return html.slice(start, end);
}

function extractHeadingContext(html: string, itemId: string): string[] {
  const esc = escapeRegex(itemId);
  const re = new RegExp(`(?:name|id)=["']${esc}["']`);
  const m = re.exec(html);
  if (!m) return [];
  const pos = m.index;

  const headingRe = /<(?:h[1-6]|legend|th)[^>]*>([^<]{1,100})/gi;
  const found: string[] = [];
  let hm: RegExpExecArray | null;
  while ((hm = headingRe.exec(html)) !== null) {
    if (hm.index >= pos) break;
    const text = hm[1].trim();
    if (text) found.push(text);
  }
  return found.slice(-3);
}

// ── 公開型 ──────────────────────────────────────────────────────────────────

export interface RenameContextItem {
  /** 現在の自動生成 ID */
  id: string;
  /** screen-items の型 */
  type: string;
  /** screen-items のラベル */
  label?: string;
  /** screen-items のプレースホルダー */
  placeholder?: string;
  /** 当該要素の周辺 HTML 断片 (LLM の命名推論に使う) */
  htmlFragment: string;
  /** 要素の直前にある見出し / legend テキスト (最大 3 件) */
  headingContext: string[];
}

export interface GetRenameContextResult {
  screenId: string;
  /** 未命名項目の一覧 (isAutoGeneratedId が true のもの) */
  unnamedItems: RenameContextItem[];
  /** 命名済み項目数 */
  namedCount: number;
}

export interface ApplyRenameMappingEntry {
  oldId: string;
  newId: string;
  screenHtmlUpdated: boolean;
  actionGroupsUpdated: string[];
  refsRenamed: number;
  warnings: string[];
}

export interface ApplyRenameMappingResult {
  screenId: string;
  succeeded: ApplyRenameMappingEntry[];
  failed: Array<{ oldId: string; newId: string; error: string }>;
}

// ── 公開 API ────────────────────────────────────────────────────────────────

/**
 * 指定画面の未命名画面項目と周辺 HTML コンテキストを返す。
 * 呼び出し元 (Claude Code) はこの情報を基に {oldId: newId} マッピングを推論する。
 */
export async function getRenameContext(screenId: string): Promise<GetRenameContextResult> {
  const siFile = (await readScreenItems(screenId)) as {
    items: Array<{ id: string; type: string; label?: string; placeholder?: string }>;
  } | null;

  if (!siFile || !Array.isArray(siFile.items)) {
    return { screenId, unnamedItems: [], namedCount: 0 };
  }

  const screenDoc = await readScreen(screenId);
  const html = screenToHtml(screenDoc);

  let namedCount = 0;
  const unnamedItems: RenameContextItem[] = [];

  for (const item of siFile.items) {
    if (!isAutoGeneratedId(item.id)) {
      namedCount++;
      continue;
    }
    unnamedItems.push({
      id: item.id,
      type: item.type ?? "string",
      label: item.label,
      placeholder: item.placeholder,
      htmlFragment: extractHtmlFragment(html, item.id),
      headingContext: extractHeadingContext(html, item.id),
    });
  }

  return { screenId, unnamedItems, namedCount };
}

/**
 * {oldId: newId} マッピングを受け取り、各エントリに対して renameScreenItemId を順次実行する。
 * 1 件の失敗は後続エントリの処理を止めない。
 */
export async function applyRenameMapping(
  screenId: string,
  mapping: Record<string, string>,
): Promise<ApplyRenameMappingResult> {
  const succeeded: ApplyRenameMappingEntry[] = [];
  const failed: Array<{ oldId: string; newId: string; error: string }> = [];

  for (const [oldId, newId] of Object.entries(mapping)) {
    try {
      const res: RenameResult = await renameScreenItemId(screenId, oldId, newId);
      succeeded.push({
        oldId,
        newId,
        screenHtmlUpdated: res.screenHtmlUpdated,
        actionGroupsUpdated: res.actionGroupsUpdated,
        refsRenamed: res.refsRenamed,
        warnings: res.warnings,
      });
    } catch (err) {
      failed.push({
        oldId,
        newId,
        error: err instanceof Error ? err.message : String(err),
      });
    }
  }

  return { screenId, succeeded, failed };
}
